feat: publish to NPM and crates.io (#17)
* Add CHANGELOG, include license and readme in release archives

* Publish to crates.io (should also support cargo-binstall automagically)

* Add npm publishing

* Split CI steps

* Bump to 0.2.0-beta.0, add draft->normal release promotion

* Add Cargo metadata

* Add badges and hide new installation methods from README for now

* Point to latest release

* Reqire tag to match Cargo.toml version

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -5,7 +5,7 @@ permissions:
 
 on:
   push:
-    tags: ['*']
+    tags: [v*]
 
 jobs:
   create-release:
@@ -16,32 +16,53 @@ jobs:
       - uses: actions/checkout@v4
         with:
           persist-credentials: false
+      - uses: actions/setup-python@v5
+
+      - name: check tag vs cargo version
+        run: |
+          pip install yq
+          tag_version=${GITHUB_REF#refs/tags/v}
+          cargo_version=$(tomlq -r '.package.version' Cargo.toml)
+          if [[ "$tag_version" != "$cargo_version" ]]; then
+            printf '::error::Version mismatch: tag for %s, cargo %s' "$tag_version" "$cargo_version"
+            exit 1
+          fi
       - uses: taiki-e/create-gh-release-action@v1      # zizmor: ignore[ref-confusion]
+        id: create-release
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
+          branch: master
+          draft: true
+          changelog: CHANGELOG.md
+    outputs:
+      version: ${{ steps.create-release.outputs.version }}
 
   upload-assets:
-    needs: create-release
+    needs: [create-release]
     strategy:
       fail-fast: false
       matrix:
         include:
-          - target: aarch64-apple-darwin
-            os: macos-latest
-          - target: aarch64-unknown-linux-gnu
-            os: ubuntu-latest
-          - target: arm-unknown-linux-gnueabihf
-            os: ubuntu-latest
-          - target: armv7-unknown-linux-gnueabihf
-            os: ubuntu-latest
-          - target: x86_64-apple-darwin
-            os: macos-latest
-          - target: x86_64-pc-windows-msvc
-            os: windows-latest
-          - target: aarch64-pc-windows-msvc
-            os: windows-latest
           - target: x86_64-unknown-linux-gnu
             os: ubuntu-latest
+            node_pair: linux-x64
+          - target: aarch64-unknown-linux-gnu
+            os: ubuntu-latest
+            node_pair: linux-arm64
+
+          - target: x86_64-apple-darwin
+            os: macos-latest
+            node_pair: darwin-x64
+          - target: aarch64-apple-darwin
+            os: macos-latest
+            node_pair: darwin-arm64
+
+          - target: x86_64-pc-windows-msvc
+            os: windows-latest
+            node_pair: windows-x64
+          - target: aarch64-pc-windows-msvc
+            os: windows-latest
+            node_pair: windows-arm64
     permissions:
       contents: write
     runs-on: ${{ matrix.os }}
@@ -49,6 +70,10 @@ jobs:
       - uses: actions/checkout@v4
         with:
           persist-credentials: false
+      - uses: actions-rust-lang/setup-rust-toolchain@v1
+        with:
+          toolchain: stable
+          cache: false
 
       # Some windows magic
       # https://github.com/nymtech/nym-vpn-client/pull/54/files#diff-7a42dc8739297053550b8882b7bf3fcc770725f51365f7b273ed5a7d9d91c329R151
@@ -75,17 +100,88 @@ jobs:
           # Note that glob pattern is not supported yet.
           bin: toggl-tracker
           checksum: sha256
+          include: LICENSE,README.md
           target: ${{ matrix.target }}
           token: ${{ secrets.GITHUB_TOKEN }}
 
-  complete-release:
-    needs: upload-assets
+      - name: Publish to NPM
+        shell: bash
+        run: |
+          cd npm/sub
+
+          target="${{ matrix.node_pair }}"
+          export node_os=${target%-*}
+          export node_arch=${target#*-}
+          export node_pkg="@sterliakov/toggl-tracker-${{ matrix.node_pair }}"
+
+          if [ "${{ matrix.os }}" = "windows-latest" ]; then
+            bin="target/${{ matrix.target }}/release/toggl-tracker.exe"
+          else
+            bin="target/${{ matrix.target }}/release/toggl-tracker"
+          fi
+          mkdir bin
+          cp "../../$bin" ./bin/
+
+          cp ../../LICENSE .
+          envsubst <package.json.tmpl >package.json
+          rm package.json.tmpl
+
+          npm publish --access public
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+          VERSION: ${{ needs.create-release.outputs.version }}
+
+  npm_base_publish:
+    name: Publish the base NPM package
+    needs: [create-release, upload-assets]
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
     steps:
-      - uses: softprops/action-gh-release@v2
+      - uses: actions/checkout@v4
         with:
-          draft: false
+          persist-credentials: false
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          registry-url: https://registry.npmjs.org
+
+      - name: Publish the package
+        shell: bash
+        run: |
+          cd npm/main
+          cp ../../README.md ./
+          cp ../../LICENSE ./
+          envsubst <package.json.tmpl >package.json
+          rm package.json.tmpl
+
+          npm publish --access public
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+          VERSION: ${{ needs.create-release.outputs.version }}
+
+  crates_io_publish:
+    name: Publish (crates.io)
+    needs: [upload-assets]
+    runs-on: ubuntu-latest
+    timeout-minutes: 25
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          persist-credentials: false
+      - uses: actions-rust-lang/setup-rust-toolchain@v1
+        with:
+          toolchain: stable
+          cache: false
+      - name: Publish
+        run: cargo publish --no-verify
+        env:
+          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
+
+  finish_release:
+    name: Promote draft release to ready
+    needs: [npm_base_publish, crates_io_publish]
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    steps:
+      - run: gh release edit "${GITHUB_REF#refs/tags/}" --draft=false
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
